#!/usr/bin/env python3
"""Generate checked-in projections of operation-registry.json.

The browser projection belongs to the standalone plugin.  The TypeScript
projection belongs to the Pluribus application and is included only when this
plugin is running from its canonical monorepo subtree.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PLUGIN_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = PLUGIN_ROOT.parent
SOURCE = PLUGIN_ROOT / "operation-registry.json"
JS_TARGET = PLUGIN_ROOT / "web" / "operation-registry.js"
TS_TARGET = REPO_ROOT / "src" / "lib" / "plugin" / "generated-operation-registry.ts"
MONOREPO_PACKAGE = REPO_ROOT / "package.json"


def _payload() -> dict:
    with SOURCE.open(encoding="utf-8") as handle:
        return json.load(handle)


def _json(value: object, indent: int = 2) -> str:
    return json.dumps(value, indent=indent, ensure_ascii=False)


def render_js(payload: dict) -> str:
    operations = {item["classType"]: item for item in payload["operations"]}
    relevant = [
        item["classType"]
        for item in payload["operations"]
        if item.get("rightsRelevant") is True
    ]
    return (
        "// Generated by tools/generate_operation_registry.py. Do not edit directly.\n"
        f"export const OPERATION_REGISTRY = Object.freeze({_json(operations)});\n\n"
        f"export const RIGHTS_RELEVANT_OPERATIONS = new Set({_json(relevant)});\n\n"
        "export function operationDefinition(classType) {\n"
        "  return OPERATION_REGISTRY[String(classType || \"\")] || null;\n"
        "}\n\n"
        "export function operationActions(classType, sourceRole = \"\") {\n"
        "  const definition = operationDefinition(classType);\n"
        "  if (!definition) return [];\n"
        "  const roleActions = definition.actionsBySourceRole?.[sourceRole];\n"
        "  return (roleActions || definition.actions || []).map((value) => ({ ...value }));\n"
        "}\n\n"
        "export function operationLabel(classType) {\n"
        "  return operationDefinition(classType)?.label || String(classType || \"Operation\");\n"
        "}\n"
    )


def render_ts(payload: dict) -> str:
    operations = {item["classType"]: item for item in payload["operations"]}
    return (
        "// Generated by comfyui-pluribus/tools/generate_operation_registry.py. Do not edit directly.\n"
        f"export const PLUGIN_OPERATION_REGISTRY = {_json(operations)} as const\n\n"
        "export type PluginOperationClassType = keyof typeof PLUGIN_OPERATION_REGISTRY\n"
        "export type PluginOperationSourceRole =\n"
        "  | 'reference_audio'\n"
        "  | 'reference_image'\n"
        "  | 'reference_video'\n"
        "  | ''\n\n"
        "export function pluginOperationActions(\n"
        "  classType: string,\n"
        "  sourceRole: string = '',\n"
        "): ReadonlyArray<{ modality: string; action: string }> {\n"
        "  const definition = PLUGIN_OPERATION_REGISTRY[\n"
        "    classType as PluginOperationClassType\n"
        "  ] as {\n"
        "    actions: ReadonlyArray<{ modality: string; action: string }>\n"
        "    actionsBySourceRole?: Record<string, ReadonlyArray<{ modality: string; action: string }>>\n"
        "  } | undefined\n"
        "  if (!definition) return []\n"
        "  return definition.actionsBySourceRole?.[sourceRole] ?? definition.actions\n"
        "}\n"
    )


def is_monorepo_checkout() -> bool:
    try:
        with MONOREPO_PACKAGE.open(encoding="utf-8") as handle:
            package = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return False
    return (
        PLUGIN_ROOT.name == "comfyui-pluribus"
        and isinstance(package, dict)
        and package.get("name") == "pluribus"
    )


def projection_targets(payload: dict) -> dict[Path, str]:
    targets = {JS_TARGET: render_js(payload)}
    if is_monorepo_checkout():
        targets[TS_TARGET] = render_ts(payload)
    return targets


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = _payload()
    targets = projection_targets(payload)
    stale = [path for path, content in targets.items() if not path.exists() or path.read_text() != content]
    if args.check:
        if stale:
            print("Stale generated operation registries:")
            for path in stale:
                print(path.relative_to(REPO_ROOT))
            return 1
        return 0
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
